load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_binary(
  name = "finch-bazel",
  srcs = glob(["src/*.scala"]),
  deps = ["@com_chuusai_shapeless_2_11_2_3_2//jar:file",
        "@com_fasterxml_jackson_core_jackson_annotations_2_8_4//jar",
        "@com_fasterxml_jackson_core_jackson_core_2_8_5//jar",
        "@com_fasterxml_jackson_core_jackson_databind_2_8_5//jar",
        "@com_fasterxml_jackson_module_jackson_module_paranamer_2_8_4//jar",
        "@com_fasterxml_jackson_module_jackson_module_scala_2_11_2_8_4//jar",
        "@com_github_ben_manes_caffeine_caffeine_2_3_4//jar",
        "@com_github_finagle_finch_circe_2_11_0_12_0//jar",
        "@com_github_finagle_finch_core_2_11_0_12_0//jar",
        "@com_github_mpilquist_simulacrum_2_11_0_10_0//jar",
        "@com_google_code_findbugs_jsr305_2_0_1//jar",
        "@com_google_guava_guava_16_0_1//jar",
        "@com_thoughtworks_paranamer_paranamer_2_8//jar",
        "@com_twitter_finagle_base_http_2_11_6_41_0//jar",
        "@com_twitter_finagle_core_2_11_6_41_0//jar",
        "@com_twitter_finagle_http_2_11_6_41_0//jar",
        "@com_twitter_finagle_netty4_http_2_11_6_41_0//jar",
        "@com_twitter_finagle_netty4_2_11_6_41_0//jar",
        "@com_twitter_finagle_toggle_2_11_6_41_0//jar",
        "@com_twitter_util_app_2_11_6_40_0//jar",
        "@com_twitter_util_cache_2_11_6_40_0//jar",
        "@com_twitter_util_codec_2_11_6_40_0//jar",
        "@com_twitter_util_collection_2_11_6_40_0//jar",
        "@com_twitter_util_core_2_11_6_40_0//jar",
        "@com_twitter_util_function_2_11_6_40_0//jar",
        "@com_twitter_util_hashing_2_11_6_40_0//jar",
        "@com_twitter_util_jvm_2_11_6_40_0//jar",
        "@com_twitter_util_lint_2_11_6_40_0//jar",
        "@com_twitter_util_logging_2_11_6_40_0//jar",
        "@com_twitter_util_registry_2_11_6_40_0//jar",
        "@com_twitter_util_stats_2_11_6_40_0//jar",
        "@com_typesafe_config_1_3_1//jar",
        "@commons_lang_commons_lang_2_6//jar",
        "@io_catbird_catbird_util_2_11_0_11_0//jar",
        "@io_circe_circe_core_2_11_0_7_0//jar",
        "@io_circe_circe_jackson28_2_11_0_7_0//jar",
        "@io_circe_circe_jawn_2_11_0_7_0//jar",
        "@io_circe_circe_numbers_2_11_0_7_0//jar",
        "@io_netty_netty_3_10_1_Final//jar",
        "@io_netty_netty_buffer_4_1_6_Final//jar",
        "@io_netty_netty_codec_4_1_6_Final//jar",
        "@io_netty_netty_codec_http_4_1_6_Final//jar",
        "@io_netty_netty_codec_socks_4_1_6_Final//jar",
        "@io_netty_netty_common_4_1_6_Final//jar",
        "@io_netty_netty_handler_4_1_6_Final//jar",
        "@io_netty_netty_handler_proxy_4_1_6_Final//jar",
        "@io_netty_netty_resolver_4_1_6_Final//jar",
        "@io_netty_netty_transport_4_1_6_Final//jar",
        "@org_scala_lang_scala_reflect_2_11_8//jar",
        "@org_scala_lang_modules_scala_parser_combinators_2_11_1_0_4//jar",
        "@org_slf4j_slf4j_api_1_7_21//jar",
        "@org_slf4j_slf4j_simple_1_7_21//jar",
        "@org_spire_math_jawn_parser_2_11_0_10_4//jar",
        "@org_typelevel_cats_core_2_11_0_9_0//jar",
        "@org_typelevel_cats_kernel_2_11_0_9_0//jar",
        "@org_typelevel_cats_macros_2_11_0_9_0//jar",
        "@org_typelevel_machinist_2_11_0_6_1//jar",
        "@org_typelevel_macro_compat_2_11_1_1_1//jar",
],
  main_class = "FinchScala",
)
